name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/webapps-deploy@v2
      with:
        app-name: munnebapp
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: .
