name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  docker_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t muneebmughal1/github-actions
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin
    - run: docker push muneebmughal1/github-actions
